formats = {
    "py" : "PYTHON",
    "txt" : "TEXT",
    "c" : "C",
    "php" : "PHP",
    "java" : "JAVA",
    "js" : "JAVASCRIPT",
    "c++" : "C++",
    "go" : "GO",
    "rust" : "RUST",
    "haskell" : "HASKELL",
    "f#" : "F#",
    "csv" : "COMMA SEPARATED VALUES",
    "html" : "HYPERTEXT MARKUP LANGUAGE",
    "rtf" : "RICH TEXT FORMAT",
    "xml" : "EXTENSIBLE MARKUP LANGUAGE",
    "json" : "JAVASCRIPT OBJECT NOTATION",
    "yaml" : "YAML AIN'T MARKUP LANGUAGE",
    "toml" : "TOM'S OBVIOUS, MINIMAL LANGUAGE",
    "ini" : "INITIALIZATION",
    "md" : "MARKDOWN",
    "log" : "LOG",
    "config" : "CONFIGURATION",
    "script" : "SCRIPT",
    "template" : "TEMPLATE",
    "data" : "DATA",
    "readme" : "README",
    "changelog" : "CHANGELOG",
    "license" : "LICENSE",
    "note" : "NOTE",
    "text" : "TEXT",
    "translation" : "TRANSLATION",
    "wiki" : "WIKI PAGE",
    "cs": "C#",
    "d": "D",
    "lua": "LUA",
    "M": "OBJECTIVE-C",
    "pl": "PERL",
    "rb": "RUBY",
    "scala": "SCALE",
    "swift": "SWIFT",
    "ts": "TYPESCRIPT",
    "vb": "VISUAL BASIC .NET",
    "sh": "bash",
}


color = {
    "black" : "\033[30m",
    "red" : "\033[31m",
    "green" : "\033[32m",
    "yellow" : "\033[33m",
    "blue" : "\033[34m",
    "purple" : "\033[35m",
    "lblue" : "\033[36m",
    "white" : "\033[37m",
    "reset" : "\033[0m",
}